### PR TITLE
Add memory store optimized subscription API

### LINKED ISSUE #987: Implement optimized version of subscribe for MemoryStore
Now that the subscribe API is implemented, we should add an optimized variation for memory store.

### PR DESCRIPTION
**Pull request by allada**
This will make memory store much more efficient for cases where subscribe is used.

closes #987

- - -
This change is [Reviewable](https://reviewable.io/reviews/nativelink/nativelink/988)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@caass 
+@adam-singer 
fyi: @zbirenbaum 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/988#-:-O-7noW_3GnmoYMN9n67:bl42blb)* status: 0 of 2 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable (waiting on @adam-singer and @caass)

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/988#-:-O-8b1bKDp5FqqLKXy5c:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @caass)

**Review by adam-singer — APPROVED** [review]
should use documentation around the new structs introduced 

> *[Reviewable](https://reviewable.io/reviews/nativelink/nativelink/988#-:-O-8b5JHD-EmFT-XmbYq:b-13ovck)* status: 1 of 2 LGTMs obtained (waiting on @caass)

**Review by caass — APPROVED** [review]
This looks pretty good, I have a few minor concerns but overall the big question is: do we want to add a dependency on [dashmap](https://docs.rs/dashmap/latest/dashmap/) in order to make the code here more readable?

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nativelink/nativelink/988#-:-O-COdCV0DBQrAle1B3O:b3fxkco)* status: 1 of 2 LGTMs obtained, and pending CI: Installation / macos-13, Publish image, Publish nativelink-worker-lre-cc, macos-13, and 4 discussions need to be resolved (waiting on @caass)

___
*[`nativelink-store/src/memory_store.rs` line 63 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-CLYBNEukfpAuD5QTr:-O-CLYBNEukfpAuD5QTs:bljfa7n) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L63)):*
> ```XML
>     store: Weak<MemoryStore>,
>     key: StoreKey<'static>,
>     receiver: Option<watch::Receiver<Result<Arc<dyn StoreSubscriptionItem>, Error>>>,
> ```

Nit: can you use the `SubscriptionSender` alias here? And declare it before this struct?
___
*[`nativelink-store/src/memory_store.rs` line 97 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-CLihZ9F09gOLLF_G9:-O-CLihZ9F09gOLLF_GA:bmag53u) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L97)):*
> ```XML
>             return;
>         };
>         store.subscription_dropped(self.key.borrow().into_owned());
> ```

Minor: I think this is more clear as an `if let` since the logic is "if we are the only handle, notify the store we're dropped". Like basically inverting this to

```rust
if let Some(store) = self.store.upgrade() {
    store.subscription_dropped(self.key.borrow().into_owned());
}
```



_Code quote:_
```XML
        let Some(store) = self.store.upgrade() else {
            return;
        };
        store.subscription_dropped(self.key.borrow().into_owned());
```
___
*[`nativelink-store/src/memory_store.rs` line 132 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-CMSZs5kqj8lyZpOi-:-O-CMSZs5kqj8lyZpOi0:b2gre0c) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L132)):*
> ```XML
>     weak_self: Weak<Self>,
>     evicting_map: EvictingMap<StoreKey<'static>, BytesWrapper, SystemTime>,
>     subscriptions: RwLock<HashMap<StoreKey<'static>, SubscriptionSender>>,
> ```

FYI this looks a lot like we want to use [dashmap](https://docs.rs/dashmap/latest/dashmap/), which is basically an auto-sharding replacement for `RwLock<HashMap>` (which leads to lower lock contention). If we're ok adding a dependency, it'd make things simpler on our side since the locking logic would be all in that crate.
___
*[`nativelink-store/src/memory_store.rs` line 157 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-CMtoADa3DAjLxIDgH:-O-CMtoADa3DAjLxIDgI:b72chrd) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L157)):*
> ```XML
> 
>     /// Tells the store that a subscription has been dropped and gives an opportunity to clean up.
>     fn subscription_dropped(&self, key: StoreKey<'static>) {
> ```

Nit: should this be more imperative? Like `drop_subscription` instead of `subscription_dropped`? I guess the more technically correct name would be like. `remove_dropped_subscription` or `notify_of_dropped_subscription`. But `subscription_dropped` sounds like it should be a `bool` or a `fn(&self) -> bool` to me.
___
*[`nativelink-store/src/memory_store.rs` line 213 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-CNISvBG9KrGhKzsnK:-O-CNISvBG9KrGhKzsnL:b13ajrx) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L213)):*
> ```XML
> 
>         self.evicting_map
>             .insert(key.borrow().into_owned(), BytesWrapper(final_buffer))
> ```

Unrelated to the current PR but I feel like this pattern of `key.borrow()` and `key.borrow().into_owned()` everywhere could probably benefit from using some traits to turn it into a proper smart pointer. Like it really wants to be a version of `Arc`, right? But like an `Arc<enum KeyKind>` basically?

I dunno, I guess it's fine for now but it generates a lot of noise around the codebase.
___
*[`nativelink-store/src/memory_store.rs` line 259 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-CNlwg3FLo0GcdznNi:-O-CNlwg3FLo0GcdznNj:b-pxsx5c) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L259)):*
> ```XML
> 
>     fn optimized_for(&self, optimization: StoreOptimizations) -> bool {
>         optimization == StoreOptimizations::SubscribeChanges
> ```

Nit: This doesn't matter at this stage but later on we'll probably want to use `matches!(optimization, StoreOptimizations::SubscribeChanges | StoreOptimizations::SomeOtherOptimization)` so it could make sense to use that syntax now.
___
*[`nativelink-store/src/memory_store.rs` line 269 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-COJQpDNjgsbJdvJwm:-O-COJQpDNjgsbJdvJwn:b-r2za18) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L269)):*
> ```XML
>             rx.mark_changed();
>             return Box::new(MemoryStoreSubscription {
>                 store: self.weak_self.clone(),
> ```

I guess it's correct to have this api where the struct stores a weak pointer to it's own allocation but it's weird to me to not use something like `Arc::clone(self).downgrade()`

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nativelink/nativelink/988)* status: 1 of 2 LGTMs obtained, and 1 discussions need to be resolved (waiting on @caass)

___
*[`nativelink-store/src/memory_store.rs` line 63 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-CLYBNEukfpAuD5QTr:-O-EYJSl1gmYPZ3NtTmv:b-92gzsa) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L63)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Nit: can you use the `SubscriptionSender` alias here? And declare it before this struct?
</blockquote></details>

These are different types:
```
watch::Sender<Result<Arc<dyn StoreSubscriptionItem>, Error>>;

vs

watch::Receiver<Result<Arc<dyn StoreSubscriptionItem>, Error>>
```
___
*[`nativelink-store/src/memory_store.rs` line 97 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-CLihZ9F09gOLLF_G9:-O-EV6dd4h4wU0jyvb5r:b-21tjsb) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L97)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Minor: I think this is more clear as an `if let` since the logic is "if we are the only handle, notify the store we're dropped". Like basically inverting this to

```rust
if let Some(store) = self.store.upgrade() {
    store.subscription_dropped(self.key.borrow().into_owned());
}
```
</blockquote></details>

I generally prefer the return-early-return-often style. In rust it's not as big of a deal, but it does reduce indentation in exchange for more lines.
___
*[`nativelink-store/src/memory_store.rs` line 132 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-CMSZs5kqj8lyZpOi-:-O-EVZi6ClVQeB-GmMD2:b-66qh7t) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L132)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

FYI this looks a lot like we want to use [dashmap](https://docs.rs/dashmap/latest/dashmap/), which is basically an auto-sharding replacement for `RwLock<HashMap>` (which leads to lower lock contention). If we're ok adding a dependency, it'd make things simpler on our side since the locking logic would be all in that crate.
</blockquote></details>

I'm not opposed to this, but instead lets do it more wide-spread to replace all cases of this.

My only concern is doing a security check/audit on them. They are big enough that I'm not worried, but our dependencies are where our security concerns live.
___
*[`nativelink-store/src/memory_store.rs` line 157 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-CMtoADa3DAjLxIDgH:-O-EVvO12AUfugOXPBlR:bdaf8v3) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L157)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Nit: should this be more imperative? Like `drop_subscription` instead of `subscription_dropped`? I guess the more technically correct name would be like. `remove_dropped_subscription` or `notify_of_dropped_subscription`. But `subscription_dropped` sounds like it should be a `bool` or a `fn(&self) -> bool` to me.
</blockquote></details>

I could make it `on_subscription_dropped`, because that's what it actually is. Done.
___
*[`nativelink-store/src/memory_store.rs` line 213 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-CNISvBG9KrGhKzsnK:-O-EWbQr7ykjBegB7TNT:bikgcxk) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L213)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Unrelated to the current PR but I feel like this pattern of `key.borrow()` and `key.borrow().into_owned()` everywhere could probably benefit from using some traits to turn it into a proper smart pointer. Like it really wants to be a version of `Arc`, right? But like an `Arc<enum KeyKind>` basically?

I dunno, I guess it's fine for now but it generates a lot of noise around the codebase.
</blockquote></details>

`Arc` is always heap allocated, which is why we use it sparingly. I know it looks weird, but the nice thing is now that all the areas are marked, it's easy to regex-replace all occurrences if we need.

The big thing I was trying to avoid was `.clone()` because it forces a copy, when most of the time `.borrow()` is enough. I also considered making it `fn to_owned(&self) -> StoreKey<'static>`, but opted out of this because there are some cases that you could move the heap allocated string instead of copying it. Yes annoying, but at the end it's not as bad as it sounds, since it's easy to change later.
___
*[`nativelink-store/src/memory_store.rs` line 259 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-CNlwg3FLo0GcdznNi:-O-EXJlsAtXNOfeRXDKr:bi44uqs) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L259)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Nit: This doesn't matter at this stage but later on we'll probably want to use `matches!(optimization, StoreOptimizations::SubscribeChanges | StoreOptimizations::SomeOtherOptimization)` so it could make sense to use that syntax now.
</blockquote></details>

Yeah, we do this in other stores.
___
*[`nativelink-store/src/memory_store.rs` line 269 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-COJQpDNjgsbJdvJwm:-O-EXZP9BUAmDzC8WVbi:b-1pq0rh) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L269)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

I guess it's correct to have this api where the struct stores a weak pointer to it's own allocation but it's weird to me to not use something like `Arc::clone(self).downgrade()`
</blockquote></details>

Yes, but doing this actually causes 2 additional needless counter changes. I think what you mean is `Arc::downgrade(self)`

In any case we have a weak ref, so might as well use it.

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nativelink/nativelink/988)* status: 1 of 2 LGTMs obtained, and 1 discussions need to be resolved (waiting on @caass)

**Review by caass — APPROVED** [review]
:lgtm:

> Reviewed 16 of 17 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nativelink/nativelink/988#-:-O-GRaR7932Aj5zMTFH3:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained

___
*[`nativelink-store/src/memory_store.rs` line 63 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-CLYBNEukfpAuD5QTr:-O-GQkfc5jWePwA9Y2be:b-ncebi6) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L63)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

These are different types:
```
watch::Sender<Result<Arc<dyn StoreSubscriptionItem>, Error>>;

vs

watch::Receiver<Result<Arc<dyn StoreSubscriptionItem>, Error>>
```
</blockquote></details>

Whoops lol
___
*[`nativelink-store/src/memory_store.rs` line 97 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-CLihZ9F09gOLLF_G9:-O-GQooaA2zM-G4LlALN:b-flevv9) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L97)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I generally prefer the return-early-return-often style. In rust it's not as big of a deal, but it does reduce indentation in exchange for more lines.
</blockquote></details>

Yea I understand, I just thought in this instance it was more clear. Either way, though, it's not a big deal.
___
*[`nativelink-store/src/memory_store.rs` line 132 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-CMSZs5kqj8lyZpOi-:-O-GR9e08lySbpptWS62:b-dxcbts) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L132)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I'm not opposed to this, but instead lets do it more wide-spread to replace all cases of this.

My only concern is doing a security check/audit on them. They are big enough that I'm not worried, but our dependencies are where our security concerns live.
</blockquote></details>

Makes sense.
___
*[`nativelink-store/src/memory_store.rs` line 213 at r2](https://reviewable.io/reviews/nativelink/nativelink/988#-O-CNISvBG9KrGhKzsnK:-O-GRQyn-ZOgfDrBLAZx:b-qqwet0) ([raw file](https://github.com/nativelink/nativelink/blob/994877cabd4be2e670e9403c6994b842c1bfbe9c/nativelink-store/src/memory_store.rs#L213)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

`Arc` is always heap allocated, which is why we use it sparingly. I know it looks weird, but the nice thing is now that all the areas are marked, it's easy to regex-replace all occurrences if we need.

The big thing I was trying to avoid was `.clone()` because it forces a copy, when most of the time `.borrow()` is enough. I also considered making it `fn to_owned(&self) -> StoreKey<'static>`, but opted out of this because there are some cases that you could move the heap allocated string instead of copying it. Yes annoying, but at the end it's not as bad as it sounds, since it's easy to change later.
</blockquote></details>

Totally

**Pull request merged**
